### ISSUE TITLE
Mica ne change pas usager

### ISSUE THREAD

**Issue by yvespayette** [obiba/mica-doc#10]
Bonjour,
Si un utilisateur de Mica change son nom ou prénom, Mica ne change pas l'affichage dans la barre de menu en haut. Même en effacant le cache.
yves payette, cartagene
yves.payette@cartagene.qc.ca

**Comment by ymarcon** [comment]
* Parles tu de Mica-server ou de Mica-drupal?
* S'agit-il d'un utilisateur ayant un compte dans Agate?

**Comment by yvespayette** [comment]
Mica server.

Je ne pense pas que ça touche agate.

Il faut éditer un nom et prénom dans le profil et mettre à jour. Le nom affiché dans la barre de menu ne change pas.

merci.

________________________________
De : Yannick Marcon <notifications@github.com>
Envoyé : 27 juin 2019 09:28
À : obiba/mica-doc
Cc : yvespayette; Author
Objet : Re: [obiba/mica-doc] Mica ne change pas usager (#10)


  *   Parles tu de Mica-server ou de Mica-drupal?
  *   S'agit-il d'un utilisateur ayant un compte dans Agate?

**Comment by ymarcon** [comment]
Je n'arrive pas à reproduire. As tu fait un refresh de la page ou alors signout puis signin?

**Comment by yvespayette** [comment]
Oui, refresh, puis signing.
Plusieurs fois.

Yaves


________________________________
De : Yannick Marcon <notifications@github.com>
Envoyé : 27 juin 2019 10:09
À : obiba/mica-doc
Cc : yvespayette; Author
Objet : Re: [obiba/mica-doc] Mica ne change pas usager (#10)


Je n'arrive pas à reproduire. As tu fait un refresh de la page ou alors signout puis signin?

**Comment by meek0** [comment]
Petite précision, vous pouvez modifier le profil à partir de votre serveur Mica? Si c'est le cas, alors c'est un utilisateur drupal.

On ne peut modifier le profile d'un utilisateur Mica que part Agate. Mica ne peut authentifier que ses utilisateurs built-in ou ceux d'Agate qui en ont la permission.

**Comment by yvespayette** [comment]
Mon nom d'utilisateur est ypayette, donc pas celui qui s'affiche. Si on peut éditer le prénom, nom pourquoi cela ne change-t-il pas le nom affiché dans la barre?
C'est un bug.

________________________________
De : meek0 <notifications@github.com>
Envoyé : 27 juin 2019 12:28
À : obiba/mica-doc
Cc : yvespayette; Author
Objet : Re: [obiba/mica-doc] Mica ne change pas usager (#10)


Petite précision, vous pouvez modifier le profil à partir de votre serveur Mica? Si c'est le cas, alors c'est un utilisateur drupal.

On ne peut modifier le profile d'un utilisateur Mica que part Agate. Mica ne peut authentifier que ses utilisateurs built-in ou ceux d'Agate qui en ont la permission.

**Comment by kazoompa** [comment]
Ce bug n'est pas reproductible dans le serveur Mica car à chaque login le profile d'usager est extrait d'Agate.

Par contre, il y a un bug dans le portail (Drupal) de Mica. 

Dans la version 7.x-36.2 de Mica Drupal il y a une nouvelle fonctionnalité permettant à l'administrateur de Drupal d'exporter les usager internes vers Agate. De plus, cette nouvelle fonctionnalité permet de _mapper_ les champs du profile de Drupal à ceux du profile d'Agate.

Ceci dit, l'affichage du barre est encore du côté Drupal, il devrait être changé. Le prochain de Drupal doit remédier ce problème.

**Comment by ymarcon** [comment]
If still relevant open a "Bug report" issue in [mica2](https://github.com/obiba/mica2/issues) repository and clearly describe the steps to reproduce.
